# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad5d00e4e83b42d261a31665ec7042439be62260ceda3d46066ed2271bbc12cc5b7fcd56e0677b45148154634e7a2d72ae91ef028a5dc76cab368358c7518067

  facebook_app_id: <%= ENV['LT_FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['LT_FACEBOOK_APP_SECRET'] %>

test:
  secret_key_base: 036e475341fe141023f22e869991ce20f34bf2f8b3caedd9bdd8cc5f34b9051fd9eccc823c17ee9bcf01a349e1ff1bbb535f29c65ff0aae0c0c389dd41904843

  facebook_app_id: <%= ENV['LT_FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['LT_FACEBOOK_APP_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV['LT_FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['LT_FACEBOOK_APP_SECRET'] %>

